### ISSUE TITLE
Fix Overflow of Text in Button

### ISSUE THREAD

**Issue by AnmolDh** [AnmolDh/Flap-n-Fly#4]
### Problem
The leaderboard button on the home page is experiencing text overflow, causing the text to extend beyond the boundaries of the button's border on certain smaller screen sizes. This issue negatively affects the visual presentation and readability of the button.

### Reproduction Steps
To reproduce the issue, follow these steps:

1. Open the website in Google Chrome.
2. Open the Chrome Developer Tools by right-clicking on the page and selecting "Inspect" or by using the keyboard shortcut `Ctrl + Shift + I`.
3. In the Developer Tools panel, click on the "Toggle device toolbar" button or press `Ctrl + Shift + M` to enable the device emulation mode.
4. Choose the device type "iPad Air" or "Samsung Galaxy S8+" from the device dropdown or enter the corresponding dimensions manually.
5. Navigate to the home page and locate the leaderboard button.
6. Observe that the text within the button overflows outside its border.

### Expected Behavior
The text within the leaderboard button should remain within the button's border on all screen sizes, ensuring readability and a visually pleasing appearance.

### Proposed Solution
To fix this issue, the following steps can be taken:

1. Adjust the CSS styles for the leaderboard button to allow for responsive behavior.
2. Use appropriate CSS techniques such as setting maximum widths, using ellipsis for long text, or wrapping the text when necessary.
3. Test the changes across various devices and screen sizes to ensure the button's text is displayed correctly without overflow.

Please feel free to assign this issue to yourself if you would like to work on it. If you have any questions or need further clarification, don't hesitate to ask.

**Comment by Mattias988** [comment]
Can I do this?
